### PR TITLE
fix: make scorm panel cover entire height in fullscreen mode

### LINKED ISSUE #96: Fullscreen Mode Not working properly
Clicking fullscreen does not make the player cover the entire screen. While the screen switches to fullscreen mode, the player's height remains fixed at the height specified in the settings.

Screenshot 2025-01-08 at 8 19 12 PM

### PR DESCRIPTION
**Pull request by Danyal-Faheem**
fixes #96.

The scorm panel would retain any custom height set or the default 450px height in fullscreen mode thus defeating the purpose of the fullscreen mode.

We now cover the entire display in fullscreen mode.

### CODE REVIEW

File: openedxscorm/static/js/src/scormxblock.js [hunk 1]
```diff
@@ -57,9 +57,15 @@ function ScormXBlock(runtime, element, settings) {
             if (settings.block_height > screen.height) {
                 $(e.target).css("height", screen.height);
             }
+            // Override height and cover entire display in fullscreen
```
Comment (ziafazal) [inline openedxscorm/static/js/src/scormxblock.js:60]: I think we should remove all this code and use `requestFullscreen` and `exitFullscreen` methods as described [here](https://www.w3schools.com/jsref/met_element_requestfullscreen.asp)

**Review by ziafazal — COMMENTED** [review]
@Danyal-Faheem I have a suggestion

**Review by ziafazal — APPROVED** [review]
👍
